site_name: Web-docs using MkDocs
site_url: https://MkDocs-web-docs.github.io/how-to-create-web-docs/

extra_css:
  - extra.css

nav:
  - Creating a web manual using MkDocs: index.md
  - Links: Links.md
  - Project Setup: Project Setup.md
  - Documentation Setup: Documentation Setup.md
  - Deploy and Customize: Deploy and Customize MkDocs.md

theme:
  name: mkdocs
  locale: ru